[build]
    command = "CI=false npm run build"
    publish = "build"
[[redirects]]
    from = "/api/*"
    to = "http://every-pet-env.eba-x3dvdddm.ap-northeast-2.elasticbeanstalk.com/:splat"
    status = 200
    force = true
