CREATE TABLE TBL_MEMBER
(
    MEMBER_ID  VARCHAR(50)  NOT NULL PRIMARY KEY,
    MEMBER_PWD VARCHAR(255) NOT NULL
);

CREATE TABLE TBL_ROLE
(
    MEMBER_ID   VARCHAR(50) NOT NULL,
    AUTHORITIES VARCHAR(50) NOT NULL,
    FOREIGN KEY (MEMBER_ID) REFERENCES TBL_MEMBER (MEMBER_ID)
);

CREATE TABLE TBL_REFRESH_TOKEN
(
    MEMBER_ID VARCHAR(50) NOT NULL PRIMARY KEY,
    REFRESH_TOKEN VARCHAR(255) NOT NULL,
    EXPIRATION_DATE VARCHAR(50) NOT NULL
);

/*INSERT INTO TBL_MEMBER (MEMBER_ID, MEMBER_PWD) VALUES
        ('admin', '1234'),
        ('user', '1234');

INSERT INTO TBL_ROLE (MEMBER_ID, AUTHORITIES) VALUES
        ('user', 'ROLE_USER'),
        ('admin', 'ROLE_ADMIN');*/